name: Deploy app to prod
on:
  push:
    branches:
      - master
    tags:
      - v1.**
jobs:
  install-build-deploy:
    name: make everything
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build
      - name: Authenticate Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy app to Google Cloud
        uses: actions/gcloud/cli@master
        with:
          args: app deploy --project=${{ secrets.CLOUDSDK_CORE_PROJECT }}
